Repository teacher-for-boss/teacher-for-boss-server, pull requests merged in 2024-03, with the labels that each got.

#107 ✨[FEAT] RedisConfig 파일 추가
  src/main/java/kr/co/teacherforboss/config/RedisConfig.java
Labels: ✨ feature

#105 🐛[FIX] 소셜로그인 전화번호 중복 체크 추가
  src/main/java/kr/co/teacherforboss/apiPayload/code/status/ErrorStatus.java
  src/main/java/kr/co/teacherforboss/config/jwt/PrincipalDetails.java
  src/main/java/kr/co/teacherforboss/repository/MemberRepository.java
  src/main/java/kr/co/teacherforboss/service/authService/AuthCommandServiceImpl.java
  src/main/java/kr/co/teacherforboss/service/examService/ExamCommandServiceImpl.java
  src/main/java/kr/co/teacherforboss/web/dto/AuthRequestDTO.java
Labels: ❤️‍🩹 fix

#111 ❤️‍🩹[FIX] ErrorStatus 수정
  src/main/java/kr/co/teacherforboss/apiPayload/code/status/ErrorStatus.java
Labels: ❤️‍🩹 fix

#108 ✨[FEAT] MemberExam에 time 컬럼 추가 및 시험 보기 리팩토링
  src/main/java/kr/co/teacherforboss/apiPayload/code/status/ErrorStatus.java
  src/main/java/kr/co/teacherforboss/converter/ExamConverter.java
  src/main/java/kr/co/teacherforboss/domain/MemberAnswer.java
  src/main/java/kr/co/teacherforboss/domain/MemberExam.java
  src/main/java/kr/co/teacherforboss/domain/QuestionChoice.java
  src/main/java/kr/co/teacherforboss/repository/QuestionChoiceRepository.java
  src/main/java/kr/co/teacherforboss/repository/QuestionRepository.java
  src/main/java/kr/co/teacherforboss/service/examService/ExamCommandService.java
  src/main/java/kr/co/teacherforboss/service/examService/ExamCommandServiceImpl.java
  src/main/java/kr/co/teacherforboss/web/controller/ExamController.java
  src/main/java/kr/co/teacherforboss/web/dto/ExamRequestDTO.java
  src/main/java/kr/co/teacherforboss/web/dto/ExamResponseDTO.java
Labels: ✨ feature, ♻️ refactor

#100 ✨[FEAT] 시험 순위 조회 API
  src/main/java/kr/co/teacherforboss/converter/ExamConverter.java
  src/main/java/kr/co/teacherforboss/domain/Question.java
  src/main/java/kr/co/teacherforboss/repository/MemberExamRepository.java
  src/main/java/kr/co/teacherforboss/service/examService/ExamQueryService.java
  src/main/java/kr/co/teacherforboss/service/examService/ExamQueryServiceImpl.java
  src/main/java/kr/co/teacherforboss/web/controller/ExamController.java
  src/main/java/kr/co/teacherforboss/web/dto/ExamResponseDTO.java
Labels: ✨ feature

#118 ✨[FEAT] 오답노트 리스트 response 데이터 추가
  src/main/java/kr/co/teacherforboss/converter/ExamConverter.java
  src/main/java/kr/co/teacherforboss/repository/MemberExamRepository.java
  src/main/java/kr/co/teacherforboss/service/examService/ExamCommandService.java
  src/main/java/kr/co/teacherforboss/service/examService/ExamCommandServiceImpl.java
  src/main/java/kr/co/teacherforboss/web/controller/ExamController.java
  src/main/java/kr/co/teacherforboss/web/dto/ExamResponseDTO.java
Labels: ✨ feature

#120 ✨[FEAT] 문제 해설 리스트 조회 API
  src/main/java/kr/co/teacherforboss/converter/ExamConverter.java
  src/main/java/kr/co/teacherforboss/service/examService/ExamQueryService.java
  src/main/java/kr/co/teacherforboss/service/examService/ExamQueryServiceImpl.java
  src/main/java/kr/co/teacherforboss/web/controller/ExamController.java
  src/main/java/kr/co/teacherforboss/web/dto/ExamResponseDTO.java
Labels: ✨ feature

#130 ✨[FEAT] 시험 치룬 횟수 조회 API
  src/main/java/kr/co/teacherforboss/converter/ExamConverter.java
  src/main/java/kr/co/teacherforboss/repository/ExamRepository.java
  src/main/java/kr/co/teacherforboss/service/examService/ExamQueryService.java
  src/main/java/kr/co/teacherforboss/service/examService/ExamQueryServiceImpl.java
  src/main/java/kr/co/teacherforboss/web/controller/ExamController.java
  src/main/java/kr/co/teacherforboss/web/dto/ExamResponseDTO.java
Labels: ✨ feature

#116 🐛[FIX] 일반로그인 GENERAL 타입 체크
  src/main/java/kr/co/teacherforboss/apiPayload/code/status/ErrorStatus.java
  src/main/java/kr/co/teacherforboss/repository/MemberRepository.java
  src/main/java/kr/co/teacherforboss/service/authService/AuthCommandServiceImpl.java
  src/main/java/kr/co/teacherforboss/web/controller/AuthController.java
Labels: ❤️‍🩹 fix

#133 ❤️‍🩹[FIX] 테스트 코드 오류 수정
  src/test/java/kr/co/teacherforboss/repository/questionRepository/QuestionRepositoryTest.java
  src/test/java/kr/co/teacherforboss/service/authService/AuthCommandServiceImplTest.java
  src/test/java/kr/co/teacherforboss/util/AuthTestUtil.java
  src/test/java/kr/co/teacherforboss/util/ExamTestUtil.java
Labels: ❤️‍🩹 fix

#135 🐞[FIX] 시험 치룬 횟수 조회 쿼리 오류 수정
  src/main/java/kr/co/teacherforboss/repository/ExamRepository.java
Labels: 🐛 bug

#127 ✨[FEAT] 같은 업종 사장님들 점수 API
  src/main/java/kr/co/teacherforboss/apiPayload/code/status/ErrorStatus.java
  src/main/java/kr/co/teacherforboss/config/ExamConfig.java
  src/main/java/kr/co/teacherforboss/converter/ExamConverter.java
  src/main/java/kr/co/teacherforboss/domain/enums/ExamQuarter.java
  src/main/java/kr/co/teacherforboss/repository/MemberExamRepository.java
  src/main/java/kr/co/teacherforboss/service/examService/ExamQueryService.java
  src/main/java/kr/co/teacherforboss/service/examService/ExamQueryServiceImpl.java
  src/main/java/kr/co/teacherforboss/web/controller/ExamController.java
  src/main/java/kr/co/teacherforboss/web/dto/ExamResponseDTO.java
Labels: ✨ feature
