Repository teacher-for-boss/teacher-for-boss-server, pull requests merged in 2024-09, with the labels that each got.

#306 🐛[FIX] 티쳐톡 Answer 티쳐의 role, level 누락 해결
  src/main/java/kr/co/teacherforboss/converter/BoardConverter.java
Labels: 🐛 bug

#304 ♻️[REFACTOR] 보스톡/티쳐톡 게시글 무한스크롤 리팩토링
  src/main/java/kr/co/teacherforboss/repository/PostRepository.java
  src/main/java/kr/co/teacherforboss/repository/QuestionRepository.java
Labels: ♻️ refactor

#309 ❤️‍🩹[FIX] 티처 프로필 수정 API - 이메일 null 허용
  src/main/java/kr/co/teacherforboss/web/dto/MemberRequestDTO.java
Labels: ❤️‍🩹 fix

#299 :bug: [FIX] 보스/티쳐 역할에 맞게 api 요청 분리
  src/main/java/kr/co/teacherforboss/apiPayload/exception/ExceptionAdvice.java
  src/main/java/kr/co/teacherforboss/config/SecurityConfig.java
  src/main/java/kr/co/teacherforboss/service/memberService/MemberCommandServiceImpl.java
  src/main/java/kr/co/teacherforboss/service/memberService/MemberQueryServiceImpl.java
  src/main/java/kr/co/teacherforboss/service/mypageService/MypageQueryServiceImpl.java
  src/main/java/kr/co/teacherforboss/service/paymentService/PaymentCommandServiceImpl.java
  src/main/java/kr/co/teacherforboss/service/paymentService/PaymentQueryServiceImpl.java
  src/main/java/kr/co/teacherforboss/web/controller/BoardController.java
  src/main/java/kr/co/teacherforboss/web/controller/MemberController.java
  src/main/java/kr/co/teacherforboss/web/controller/MypageController.java
  src/main/java/kr/co/teacherforboss/web/controller/PaymentController.java
Labels: ❤️‍🩹 fix
