Repository teacher-for-boss/teacher-for-boss-server, pull requests merged in 2024-02, with the labels that each got.

#75 🩹 [FIX] 휴대폰 인증번호 확인 request validation 수정
  src/main/java/kr/co/teacherforboss/web/dto/AuthRequestDTO.java
Labels: ❤️‍🩹 fix

#61 ♻️[REFACTOR] JWT 에러 로그 삭제
  src/main/java/kr/co/teacherforboss/apiPayload/code/status/ErrorStatus.java
  src/main/java/kr/co/teacherforboss/config/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/kr/co/teacherforboss/config/jwt/filter/JwtExceptionFilter.java
  src/main/java/kr/co/teacherforboss/service/authService/AuthQueryServiceImpl.java
Labels: ♻️ refactor

#71 ♻️[REFACTOR] @Valid Exception Response 구조 변경
  src/main/java/kr/co/teacherforboss/apiPayload/ApiResponse.java
  src/main/java/kr/co/teacherforboss/apiPayload/exception/ExceptionAdvice.java
Labels: ♻️ refactor

#66 ✅ [TEST] 프로필 조회 API 테스트
  src/test/java/kr/co/teacherforboss/service/memberService/MemberQueryServiceImplTest.java
Labels: ✅ test

#68 ✅ [TEST] 비밀번호 찾기 API 테스트
  src/test/java/kr/co/teacherforboss/service/authService/AuthCommandServiceImplTest.java
  src/test/java/kr/co/teacherforboss/util/AuthTestUtil.java
Labels: ✅ test

#73 ❤️‍🩹[FIX] 회원가입 약관동의 NPE 해결
  src/main/java/kr/co/teacherforboss/validation/validator/CheckTrueOrFalseValidator.java
Labels: ❤️‍🩹 fix

#84 ❤️‍🩹[FIX] 회원가입 이메일 중복 오류 수정
  src/main/java/kr/co/teacherforboss/repository/MemberRepository.java
  src/main/java/kr/co/teacherforboss/service/authService/AuthCommandServiceImpl.java
Labels: ❤️‍🩹 fix

#93 ✨[FEAT] 이메일 및 전화번호 인증 중복체크
  src/main/java/kr/co/teacherforboss/apiPayload/code/status/ErrorStatus.java
  src/main/java/kr/co/teacherforboss/repository/MemberRepository.java
  src/main/java/kr/co/teacherforboss/service/authService/AuthCommandServiceImpl.java
Labels: ✨ feature

#82 ✨[FEAT] 시험 결과 조회 API
  src/main/java/kr/co/teacherforboss/apiPayload/code/status/ErrorStatus.java
  src/main/java/kr/co/teacherforboss/converter/ExamConverter.java
  src/main/java/kr/co/teacherforboss/repository/ExamRepository.java
  src/main/java/kr/co/teacherforboss/repository/MemberAnswerRepository.java
  src/main/java/kr/co/teacherforboss/repository/MemberExamRepository.java
  src/main/java/kr/co/teacherforboss/service/examService/ExamCommandService.java
  src/main/java/kr/co/teacherforboss/service/examService/ExamCommandServiceImpl.java
  src/main/java/kr/co/teacherforboss/web/controller/ExamController.java
  src/main/java/kr/co/teacherforboss/web/dto/ExamResponseDTO.java
Labels: ✨ feature

#97 ✨ [FEAT] 로그인 API response 사용자 이름 추가
  src/main/java/kr/co/teacherforboss/config/jwt/JwtTokenProvider.java
  src/main/java/kr/co/teacherforboss/web/controller/AuthController.java
  src/main/java/kr/co/teacherforboss/web/dto/AuthResponseDTO.java
Labels: ✨ feature

#95 ✨[FEAT] 오답노트 리스트 조회 API
  src/main/java/kr/co/teacherforboss/apiPayload/code/status/ErrorStatus.java
  src/main/java/kr/co/teacherforboss/converter/ExamConverter.java
  src/main/java/kr/co/teacherforboss/domain/Question.java
  src/main/java/kr/co/teacherforboss/repository/MemberAnswerRepository.java
  src/main/java/kr/co/teacherforboss/repository/MemberExamRepository.java
  src/main/java/kr/co/teacherforboss/service/examService/ExamCommandService.java
  src/main/java/kr/co/teacherforboss/service/examService/ExamCommandServiceImpl.java
  src/main/java/kr/co/teacherforboss/web/controller/ExamController.java
  src/main/java/kr/co/teacherforboss/web/dto/ExamResponseDTO.java
Labels: ✨ feature

#91 ✨[FEAT] 시험 문항 리스트 조회 API
  src/main/java/kr/co/teacherforboss/apiPayload/code/status/ErrorStatus.java
  src/main/java/kr/co/teacherforboss/converter/ExamConverter.java
  src/main/java/kr/co/teacherforboss/repository/ExamRepository.java
  src/main/java/kr/co/teacherforboss/repository/QuestionRepository.java
  src/main/java/kr/co/teacherforboss/service/examService/ExamQueryService.java
  src/main/java/kr/co/teacherforboss/service/examService/ExamQueryServiceImpl.java
  src/main/java/kr/co/teacherforboss/web/controller/ExamController.java
  src/main/java/kr/co/teacherforboss/web/dto/ExamResponseDTO.java
Labels: ✨ feature
