Repository teacher-for-boss/teacher-for-boss-server, pull requests merged in 2024-07, with the labels that each got.

#226 ✨[FEAT] 보스톡 댓글 추천/비추천 API
  src/main/java/kr/co/teacherforboss/converter/BoardConverter.java
  src/main/java/kr/co/teacherforboss/converter/CommentConverter.java
  src/main/java/kr/co/teacherforboss/domain/Comment.java
  src/main/java/kr/co/teacherforboss/domain/CommentLike.java
  src/main/java/kr/co/teacherforboss/repository/CommentLikeRepository.java
  src/main/java/kr/co/teacherforboss/repository/CommentRepository.java
  src/main/java/kr/co/teacherforboss/service/boardService/BoardCommandService.java
  src/main/java/kr/co/teacherforboss/service/boardService/BoardCommandServiceImpl.java
  src/main/java/kr/co/teacherforboss/web/controller/BoardController.java
  src/main/java/kr/co/teacherforboss/web/dto/BoardResponseDTO.java
Labels: ✨ feature

#241 🐛[FIX] 북마크 API response값 수정
  src/main/java/kr/co/teacherforboss/converter/BoardConverter.java
Labels: ❤️‍🩹 fix

#230 ✨[FEAT] 티쳐톡 질문 리스트 조회
  src/main/java/kr/co/teacherforboss/converter/BoardConverter.java
  src/main/java/kr/co/teacherforboss/domain/Question.java
  src/main/java/kr/co/teacherforboss/domain/enums/QuestionCategory.java
  src/main/java/kr/co/teacherforboss/repository/AnswerRepository.java
  src/main/java/kr/co/teacherforboss/repository/QuestionBookmarkRepository.java
  src/main/java/kr/co/teacherforboss/repository/QuestionLikeRepository.java
  src/main/java/kr/co/teacherforboss/repository/QuestionRepository.java
  src/main/java/kr/co/teacherforboss/service/boardService/BoardQueryService.java
  src/main/java/kr/co/teacherforboss/service/boardService/BoardQueryServiceImpl.java
  src/main/java/kr/co/teacherforboss/web/controller/BoardController.java
  src/main/java/kr/co/teacherforboss/web/dto/BoardResponseDTO.java
Labels: ✨ feature

#237 ✨[FEAT] 보스톡 댓글 리스트 조회 API
  src/main/java/kr/co/teacherforboss/converter/BoardConverter.java
  src/main/java/kr/co/teacherforboss/repository/AnswerRepository.java
  src/main/java/kr/co/teacherforboss/repository/CommentLikeRepository.java
  src/main/java/kr/co/teacherforboss/repository/CommentRepository.java
  src/main/java/kr/co/teacherforboss/repository/PostRepository.java
  src/main/java/kr/co/teacherforboss/repository/QuestionRepository.java
  src/main/java/kr/co/teacherforboss/repository/TeacherInfoRepository.java
  src/main/java/kr/co/teacherforboss/service/boardService/BoardQueryService.java
  src/main/java/kr/co/teacherforboss/service/boardService/BoardQueryServiceImpl.java
  src/main/java/kr/co/teacherforboss/web/controller/BoardController.java
  src/main/java/kr/co/teacherforboss/web/dto/BoardResponseDTO.java
  src/main/java/kr/co/teacherforboss/web/dto/MemberResponseDTO.java
Labels: ✨ feature

#242 ✨[FEAT] 보스톡 키워드 검색 API
  src/main/java/kr/co/teacherforboss/apiPayload/code/status/ErrorStatus.java
  src/main/java/kr/co/teacherforboss/repository/PostRepository.java
  src/main/java/kr/co/teacherforboss/service/boardService/BoardQueryService.java
  src/main/java/kr/co/teacherforboss/service/boardService/BoardQueryServiceImpl.java
  src/main/java/kr/co/teacherforboss/web/controller/BoardController.java
Labels: ✨ feature

#249 ✨[FEAT] 보스톡 댓글 삭제 API
  src/main/java/kr/co/teacherforboss/converter/BoardConverter.java
  src/main/java/kr/co/teacherforboss/repository/CommentRepository.java
  src/main/java/kr/co/teacherforboss/service/boardService/BoardCommandService.java
  src/main/java/kr/co/teacherforboss/service/boardService/BoardCommandServiceImpl.java
  src/main/java/kr/co/teacherforboss/web/controller/BoardController.java
  src/main/java/kr/co/teacherforboss/web/dto/BoardResponseDTO.java
Labels: ✨ feature

#243 ✨[FEAT] 티쳐톡 질문 키워드 검색
  src/main/java/kr/co/teacherforboss/converter/BoardConverter.java
  src/main/java/kr/co/teacherforboss/repository/AnswerRepository.java
  src/main/java/kr/co/teacherforboss/repository/QuestionRepository.java
  src/main/java/kr/co/teacherforboss/service/boardService/BoardQueryService.java
  src/main/java/kr/co/teacherforboss/service/boardService/BoardQueryServiceImpl.java
  src/main/java/kr/co/teacherforboss/web/controller/BoardController.java
  src/main/java/kr/co/teacherforboss/web/dto/BoardResponseDTO.java
Labels: ✨ feature, ❤️‍🩹 fix

#258 ❤️‍🩹[FIX] 티쳐톡 질문 리스트 조회 시 카테고리 전체인 경우 추가
  src/main/java/kr/co/teacherforboss/repository/QuestionRepository.java
  src/main/java/kr/co/teacherforboss/service/boardService/BoardQueryServiceImpl.java
Labels: ❤️‍🩹 fix

#253 ✨[FEAT] 계좌 정보 조회 API
  src/main/java/kr/co/teacherforboss/apiPayload/code/status/ErrorStatus.java
  src/main/java/kr/co/teacherforboss/converter/PaymentConverter.java
  src/main/java/kr/co/teacherforboss/repository/TeacherInfoRepository.java
  src/main/java/kr/co/teacherforboss/service/paymentService/PaymentQueryService.java
  src/main/java/kr/co/teacherforboss/service/paymentService/PaymentQueryServiceImpl.java
  src/main/java/kr/co/teacherforboss/util/AES256Util.java
  src/main/java/kr/co/teacherforboss/web/controller/PaymentController.java
  src/main/java/kr/co/teacherforboss/web/dto/PaymentResponseDTO.java
  src/test/java/kr/co/teacherforboss/unit/AES256UtilTest.java
Labels: ✨ feature

#259 ✨[FEAT] 프로필 수정 API
  src/main/java/kr/co/teacherforboss/apiPayload/code/status/ErrorStatus.java
  src/main/java/kr/co/teacherforboss/converter/MemberConverter.java
  src/main/java/kr/co/teacherforboss/domain/TeacherInfo.java
  src/main/java/kr/co/teacherforboss/domain/enums/BooleanType.java
  src/main/java/kr/co/teacherforboss/service/memberService/MemberCommandService.java
  src/main/java/kr/co/teacherforboss/service/memberService/MemberCommandServiceImpl.java
  src/main/java/kr/co/teacherforboss/web/controller/MemberController.java
  src/main/java/kr/co/teacherforboss/web/dto/MemberRequestDTO.java
  src/main/java/kr/co/teacherforboss/web/dto/MemberResponseDTO.java
Labels: ✨ feature

#255 ✨[FEAT] 회원 탈퇴 API
  src/main/java/kr/co/teacherforboss/converter/AuthConverter.java
  src/main/java/kr/co/teacherforboss/domain/Member.java
  src/main/java/kr/co/teacherforboss/repository/TeacherInfoRepository.java
  src/main/java/kr/co/teacherforboss/service/authService/AuthCommandService.java
  src/main/java/kr/co/teacherforboss/service/authService/AuthCommandServiceImpl.java
  src/main/java/kr/co/teacherforboss/web/controller/AuthController.java
  src/main/java/kr/co/teacherforboss/web/controller/MemberController.java
  src/main/java/kr/co/teacherforboss/web/dto/AuthResponseDTO.java
Labels: ✨ feature

#269 ❤️‍🩹[FIX] 티쳐톡 답변 채택 로직 수정
  src/main/java/kr/co/teacherforboss/apiPayload/code/status/ErrorStatus.java
  src/main/java/kr/co/teacherforboss/domain/Question.java
  src/main/java/kr/co/teacherforboss/domain/TeacherSelectInfo.java
  src/main/java/kr/co/teacherforboss/repository/TeacherSelectInfoRepository.java
  src/main/java/kr/co/teacherforboss/service/authService/AuthCommandServiceImpl.java
  src/main/java/kr/co/teacherforboss/service/boardService/BoardCommandServiceImpl.java
  src/main/java/kr/co/teacherforboss/service/memberService/MemberCommandServiceImpl.java
Labels: ❤️‍🩹 fix

#270 ✨[FEAT] 홈 뷰 인기 컨텐츠 조회 API
  src/main/java/kr/co/teacherforboss/TeacherforbossApplication.java
  src/main/java/kr/co/teacherforboss/apiPayload/code/status/ErrorStatus.java
  src/main/java/kr/co/teacherforboss/apiPayload/exception/handler/HomeHandler.java
  src/main/java/kr/co/teacherforboss/config/RedisConfig.java
  src/main/java/kr/co/teacherforboss/converter/BoardConverter.java
  src/main/java/kr/co/teacherforboss/converter/MemberConverter.java
  src/main/java/kr/co/teacherforboss/domain/common/BaseEntity.java
  src/main/java/kr/co/teacherforboss/repository/MemberRepository.java
  src/main/java/kr/co/teacherforboss/repository/PostRepository.java
  src/main/java/kr/co/teacherforboss/repository/QuestionRepository.java
  src/main/java/kr/co/teacherforboss/repository/TeacherSelectInfoRepository.java
  src/main/java/kr/co/teacherforboss/service/homeService/HomeQueryService.java
  src/main/java/kr/co/teacherforboss/service/homeService/HomeQueryServiceImpl.java
  src/main/java/kr/co/teacherforboss/web/controller/HomeController.java
  src/main/java/kr/co/teacherforboss/web/dto/HomeResponseDTO.java
Labels: ✨ feature

#276 ✨[FEAT] 계정 정보 조회 API
  src/main/java/kr/co/teacherforboss/converter/MemberConverter.java
  src/main/java/kr/co/teacherforboss/web/controller/MemberController.java
  src/main/java/kr/co/teacherforboss/web/dto/MemberResponseDTO.java
Labels: ✨ feature

#261 ✨[FEAT] 내가 답변한 질문글 조회 API
  src/main/java/kr/co/teacherforboss/converter/BoardConverter.java
  src/main/java/kr/co/teacherforboss/repository/QuestionRepository.java
  src/main/java/kr/co/teacherforboss/service/mypageService/MypageQueryService.java
  src/main/java/kr/co/teacherforboss/service/mypageService/MypageQueryServiceImpl.java
  src/main/java/kr/co/teacherforboss/web/controller/MypageController.java
  src/main/java/kr/co/teacherforboss/web/dto/MypageResponseDTO.java
Labels: ✨ feature

#265 ✨[FEAT] 프로필 조회 API res body 추가
  src/main/java/kr/co/teacherforboss/converter/MemberConverter.java
  src/main/java/kr/co/teacherforboss/domain/enums/Level.java
  src/main/java/kr/co/teacherforboss/repository/AnswerRepository.java
  src/main/java/kr/co/teacherforboss/service/memberService/MemberQueryService.java
  src/main/java/kr/co/teacherforboss/service/memberService/MemberQueryServiceImpl.java
  src/main/java/kr/co/teacherforboss/web/controller/MemberController.java
  src/main/java/kr/co/teacherforboss/web/dto/MemberResponseDTO.java
  src/test/java/kr/co/teacherforboss/service/memberService/MemberQueryServiceImplTest.java
  src/test/java/kr/co/teacherforboss/util/MemberTestUtil.java
Labels: ✨ feature

#272 ✨[FEAT] 계좌 변경 API
  src/main/java/kr/co/teacherforboss/apiPayload/code/status/ErrorStatus.java
  src/main/java/kr/co/teacherforboss/converter/PaymentConverter.java
  src/main/java/kr/co/teacherforboss/domain/TeacherInfo.java
  src/main/java/kr/co/teacherforboss/service/paymentService/PaymentCommandService.java
  src/main/java/kr/co/teacherforboss/service/paymentService/PaymentCommandServiceImpl.java
  src/main/java/kr/co/teacherforboss/web/controller/PaymentController.java
  src/main/java/kr/co/teacherforboss/web/dto/MemberRequestDTO.java
  src/main/java/kr/co/teacherforboss/web/dto/PaymentRequestDTO.java
  src/main/java/kr/co/teacherforboss/web/dto/PaymentResponseDTO.java
Labels: ✨ feature

#280 ✨[FEAT] 티포 환전 완료 처리 API
  src/main/java/kr/co/teacherforboss/apiPayload/code/status/ErrorStatus.java
  src/main/java/kr/co/teacherforboss/converter/PaymentConverter.java
  src/main/java/kr/co/teacherforboss/domain/Exchange.java
  src/main/java/kr/co/teacherforboss/repository/ExchangeRepository.java
  src/main/java/kr/co/teacherforboss/service/paymentService/PaymentCommandService.java
  src/main/java/kr/co/teacherforboss/service/paymentService/PaymentCommandServiceImpl.java
  src/main/java/kr/co/teacherforboss/web/controller/PaymentController.java
  src/main/java/kr/co/teacherforboss/web/dto/PaymentResponseDTO.java
Labels: ✨ feature
