Repository teacher-for-boss/teacher-for-boss-server, pull requests merged in 2024-01, with the labels that each got.

#6 ❤️‍🩹 [FIX] BaseEntity & Member 엔티티 수정
  src/main/java/kr/co/teacherforboss/domain/Member.java
  src/main/java/kr/co/teacherforboss/domain/common/BaseEntity.java
  src/main/java/kr/co/teacherforboss/domain/enums/Role.java
Labels: ❤️‍🩹 fix

#9 🔧 [FEAT] Swagger config
  build.gradle
  src/main/java/kr/co/teacherforboss/config/SecurityConfig.java
  src/main/java/kr/co/teacherforboss/config/SwaggerConfig.java
  src/main/java/kr/co/teacherforboss/web/controller/TempController.java
Labels: ✨ feature

#11 :sparkles: [FEAT] EmailAuth 엔티티 추가
  src/main/java/kr/co/teacherforboss/domain/EmailAuth.java
  src/main/java/kr/co/teacherforboss/domain/enums/Purpose.java
Labels: ✨ feature

#15 ✨ [FEAT] Member 엔티티 컬럼 추가
  src/main/java/kr/co/teacherforboss/domain/Member.java
  src/main/java/kr/co/teacherforboss/domain/common/BaseEntity.java
  src/main/java/kr/co/teacherforboss/domain/enums/Gender.java
Labels: ✨ feature

#20 ✨[FEAT] 이메일 인증 API
  build.gradle
  src/main/java/kr/co/teacherforboss/apiPayload/ApiResponse.java
  src/main/java/kr/co/teacherforboss/apiPayload/code/status/ErrorStatus.java
  src/main/java/kr/co/teacherforboss/apiPayload/exception/ExceptionAdvice.java
  src/main/java/kr/co/teacherforboss/apiPayload/exception/handler/MailHandler.java
  src/main/java/kr/co/teacherforboss/config/MailConfig.java
  src/main/java/kr/co/teacherforboss/config/SecurityConfig.java
  src/main/java/kr/co/teacherforboss/converter/AuthConverter.java
  src/main/java/kr/co/teacherforboss/domain/EmailAuth.java
  src/main/java/kr/co/teacherforboss/domain/Member.java
  src/main/java/kr/co/teacherforboss/domain/common/BaseEntity.java
  src/main/java/kr/co/teacherforboss/domain/enums/Purpose.java
  src/main/java/kr/co/teacherforboss/domain/vo/mailVO/CodeMail.java
  src/main/java/kr/co/teacherforboss/domain/vo/mailVO/Mail.java
  src/main/java/kr/co/teacherforboss/repository/EmailAuthRepository.java
  src/main/java/kr/co/teacherforboss/service/AuthService/AuthCommandService.java
  src/main/java/kr/co/teacherforboss/service/AuthService/AuthCommandServiceImpl.java
  src/main/java/kr/co/teacherforboss/service/MailService/MailCommandService.java
  src/main/java/kr/co/teacherforboss/service/MailService/MailCommandServiceImpl.java
  src/main/java/kr/co/teacherforboss/validation/annotation/CheckPurpose.java
  src/main/java/kr/co/teacherforboss/validation/validator/CheckPurposeValidator.java
  src/main/java/kr/co/teacherforboss/web/controller/AuthController.java
  src/main/java/kr/co/teacherforboss/web/controller/TempController.java
  src/main/java/kr/co/teacherforboss/web/dto/AuthRequestDTO.java
  src/main/java/kr/co/teacherforboss/web/dto/AuthResponseDTO.java
  src/main/resources/templates/code.html
  src/test/java/kr/co/teacherforboss/service/AuthService/AuthCommandServiceImplTest.java
Labels: ✨ feature

#24 ✨[FEAT] 이메일 인증 확인 API
  src/main/java/kr/co/teacherforboss/apiPayload/code/status/ErrorStatus.java
  src/main/java/kr/co/teacherforboss/converter/AuthConverter.java
  src/main/java/kr/co/teacherforboss/domain/EmailAuth.java
  src/main/java/kr/co/teacherforboss/domain/vo/mailVO/CodeMail.java
  src/main/java/kr/co/teacherforboss/service/AuthService/AuthCommandService.java
  src/main/java/kr/co/teacherforboss/service/AuthService/AuthCommandServiceImpl.java
  src/main/java/kr/co/teacherforboss/validation/validator/CheckPurposeValidator.java
  src/main/java/kr/co/teacherforboss/web/controller/AuthController.java
  src/main/java/kr/co/teacherforboss/web/dto/AuthRequestDTO.java
  src/main/java/kr/co/teacherforboss/web/dto/AuthResponseDTO.java
  src/test/java/kr/co/teacherforboss/service/AuthService/AuthCommandServiceImplTest.java
Labels: ✨ feature

#35 ✨[FEAT] Access Token 재발급 API
  build.gradle
  src/main/java/kr/co/teacherforboss/apiPayload/code/status/ErrorStatus.java
  src/main/java/kr/co/teacherforboss/config/JwtSecurityConfig.java
  src/main/java/kr/co/teacherforboss/config/RedisConfig.java
  src/main/java/kr/co/teacherforboss/config/SecurityConfig.java
  src/main/java/kr/co/teacherforboss/config/jwt/JwtAccessDeniedHandler.java
  src/main/java/kr/co/teacherforboss/config/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/kr/co/teacherforboss/config/jwt/JwtAuthenticationFilter.java
  src/main/java/kr/co/teacherforboss/config/jwt/JwtExceptionFilter.java
  src/main/java/kr/co/teacherforboss/config/jwt/JwtFilter.java
  src/main/java/kr/co/teacherforboss/config/jwt/JwtSecurityConfig.java
  src/main/java/kr/co/teacherforboss/config/jwt/JwtTokenProvider.java
  src/main/java/kr/co/teacherforboss/config/jwt/PrincipalDetails.java
  src/main/java/kr/co/teacherforboss/config/jwt/TokenInfo.java
  src/main/java/kr/co/teacherforboss/config/jwt/TokenManager.java
  src/main/java/kr/co/teacherforboss/config/jwt/TokenProvider.java
  src/main/java/kr/co/teacherforboss/config/jwt/exception/MyAccessDeniedHandler.java
  src/main/java/kr/co/teacherforboss/config/jwt/exception/MyAuthenticationEntryPoint.java
  src/main/java/kr/co/teacherforboss/converter/AuthConverter.java
  src/main/java/kr/co/teacherforboss/domain/Member.java
  src/main/java/kr/co/teacherforboss/repository/MemberRepository.java
  src/main/java/kr/co/teacherforboss/service/TempService/TempCommandService.java
  src/main/java/kr/co/teacherforboss/service/TempService/TempCommandServiceImpl.java
  src/main/java/kr/co/teacherforboss/service/authService/AuthCommandService.java
  src/main/java/kr/co/teacherforboss/service/authService/AuthCommandServiceImpl.java
  src/main/java/kr/co/teacherforboss/service/authService/AuthQueryService.java
  src/main/java/kr/co/teacherforboss/service/authService/AuthQueryServiceImpl.java
  src/main/java/kr/co/teacherforboss/service/mailService/MailCommandService.java
  src/main/java/kr/co/teacherforboss/service/mailService/MailCommandServiceImpl.java
  src/main/java/kr/co/teacherforboss/service/tempService/TempCommandService.java
  src/main/java/kr/co/teacherforboss/service/tempService/TempCommandServiceImpl.java
  src/main/java/kr/co/teacherforboss/service/tempService/TempQueryService.java
  src/main/java/kr/co/teacherforboss/service/tempService/TempQueryServiceImpl.java
  src/main/java/kr/co/teacherforboss/util/GrandUtil.java
  src/main/java/kr/co/teacherforboss/web/controller/AuthController.java
  src/main/java/kr/co/teacherforboss/web/dto/AuthRequestDTO.java
  src/main/java/kr/co/teacherforboss/web/dto/AuthResponseDTO.java
  src/main/java/kr/co/teacherforboss/web/dto/TokenDto.java
  src/test/java/kr/co/teacherforboss/service/authService/AuthCommandServiceImplTest.java
Labels: ✨ feature

#36 ✨[FEAT] 비밀번호 찾기 API
  src/main/java/kr/co/teacherforboss/converter/AuthConverter.java
  src/main/java/kr/co/teacherforboss/repository/EmailAuthRepository.java
  src/main/java/kr/co/teacherforboss/repository/MemberRepository.java
  src/main/java/kr/co/teacherforboss/service/authService/AuthCommandService.java
  src/main/java/kr/co/teacherforboss/service/authService/AuthCommandServiceImpl.java
  src/main/java/kr/co/teacherforboss/web/controller/AuthController.java
  src/main/java/kr/co/teacherforboss/web/dto/AuthRequestDTO.java
  src/main/java/kr/co/teacherforboss/web/dto/AuthResponseDTO.java
Labels: ✨ feature

#39 ♻️[REFACTOR] JWT 관련 코드 리팩토링
  src/main/java/kr/co/teacherforboss/config/JwtSecurityConfig.java
  src/main/java/kr/co/teacherforboss/config/RedisConfig.java
  src/main/java/kr/co/teacherforboss/config/SecurityConfig.java
  src/main/java/kr/co/teacherforboss/config/jwt/JwtTokenProvider.java
  src/main/java/kr/co/teacherforboss/config/jwt/TokenManager.java
  src/main/java/kr/co/teacherforboss/config/jwt/exception/JwtAccessDeniedHandler.java
  src/main/java/kr/co/teacherforboss/config/jwt/exception/JwtAuthenticationEntryPoint.java
  src/main/java/kr/co/teacherforboss/config/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/kr/co/teacherforboss/config/jwt/filter/JwtExceptionFilter.java
  src/main/java/kr/co/teacherforboss/service/authService/AuthCommandService.java
  src/main/java/kr/co/teacherforboss/service/authService/AuthCommandServiceImpl.java
  src/main/java/kr/co/teacherforboss/validation/annotation/ExistPrincipalDetails.java
  src/main/java/kr/co/teacherforboss/validation/validator/PrincipalDetailsExistValidator.java
  src/main/java/kr/co/teacherforboss/web/controller/AuthController.java
Labels: ♻️ refactor

#40 ✨[FEAT] 비밀번호 재설정 API
  src/main/java/kr/co/teacherforboss/converter/AuthConverter.java
  src/main/java/kr/co/teacherforboss/service/authService/AuthCommandService.java
  src/main/java/kr/co/teacherforboss/service/authService/AuthCommandServiceImpl.java
  src/main/java/kr/co/teacherforboss/util/PasswordUtil.java
  src/main/java/kr/co/teacherforboss/web/controller/AuthController.java
  src/main/java/kr/co/teacherforboss/web/dto/AuthRequestDTO.java
  src/main/java/kr/co/teacherforboss/web/dto/AuthResponseDTO.java
Labels: ✨ feature

#42 ✨[FEAT] 휴대폰 인증 API
  build.gradle
  src/main/java/kr/co/teacherforboss/converter/AuthConverter.java
  src/main/java/kr/co/teacherforboss/domain/PhoneAuth.java
  src/main/java/kr/co/teacherforboss/domain/vo/smsVO/CodeSMS.java
  src/main/java/kr/co/teacherforboss/domain/vo/smsVO/SMS.java
  src/main/java/kr/co/teacherforboss/service/authService/AuthCommandService.java
  src/main/java/kr/co/teacherforboss/service/authService/AuthCommandServiceImpl.java
  src/main/java/kr/co/teacherforboss/util/SmsUtil.java
  src/main/java/kr/co/teacherforboss/web/controller/AuthController.java
  src/main/java/kr/co/teacherforboss/web/dto/AuthRequestDTO.java
  src/main/java/kr/co/teacherforboss/web/dto/AuthResponseDTO.java
Labels: ✨ feature

#43 ✨[FEAT] 사전정보 저장 API
  src/main/java/kr/co/teacherforboss/apiPayload/code/status/ErrorStatus.java
  src/main/java/kr/co/teacherforboss/config/jwt/JwtTokenProvider.java
  src/main/java/kr/co/teacherforboss/converter/MemberConverter.java
  src/main/java/kr/co/teacherforboss/domain/MemberSurvey.java
  src/main/java/kr/co/teacherforboss/domain/enums/Survey.java
  src/main/java/kr/co/teacherforboss/repository/MemberSurveyRepository.java
  src/main/java/kr/co/teacherforboss/service/authService/AuthCommandService.java
  src/main/java/kr/co/teacherforboss/service/authService/AuthCommandServiceImpl.java
  src/main/java/kr/co/teacherforboss/service/memberService/MemberCommandService.java
  src/main/java/kr/co/teacherforboss/service/memberService/MemberCommandServiceImpl.java
  src/main/java/kr/co/teacherforboss/util/SecurityUtil.java
  src/main/java/kr/co/teacherforboss/validation/annotation/CheckSurvey.java
  src/main/java/kr/co/teacherforboss/validation/validator/CheckSurveyValidator.java
  src/main/java/kr/co/teacherforboss/web/controller/MemberController.java
  src/main/java/kr/co/teacherforboss/web/dto/AuthRequestDTO.java
  src/main/java/kr/co/teacherforboss/web/dto/MemberRequestDTO.java
  src/main/java/kr/co/teacherforboss/web/dto/MemberResponseDTO.java
Labels: ✨ feature

#46 ❤️‍🩹[FIX] 사전정보 저장 Request 저장
  src/main/java/kr/co/teacherforboss/web/dto/MemberRequestDTO.java
Labels: ❤️‍🩹 fix

#47 ✨[FEAT] 프로필 조회 API
  src/main/java/kr/co/teacherforboss/converter/MemberConverter.java
  src/main/java/kr/co/teacherforboss/domain/enums/LoginType.java
  src/main/java/kr/co/teacherforboss/repository/MemberRepository.java
  src/main/java/kr/co/teacherforboss/service/memberService/MemberQueryService.java
  src/main/java/kr/co/teacherforboss/service/memberService/MemberQueryServiceImpl.java
  src/main/java/kr/co/teacherforboss/web/controller/MemberController.java
  src/main/java/kr/co/teacherforboss/web/dto/MemberResponseDTO.java
Labels: ✨ feature

#53 ❤️‍🩹[FIX] 사전정보 2번 list로 수정
  src/main/java/kr/co/teacherforboss/converter/MemberConverter.java
  src/main/java/kr/co/teacherforboss/domain/MemberSurvey.java
  src/main/java/kr/co/teacherforboss/domain/converter/SurveyListConverter.java
  src/main/java/kr/co/teacherforboss/validation/annotation/CheckSurvey.java
  src/main/java/kr/co/teacherforboss/validation/validator/AbstractCheckSurveyValidator.java
  src/main/java/kr/co/teacherforboss/validation/validator/CheckSurveyValidatorForInteger.java
  src/main/java/kr/co/teacherforboss/validation/validator/CheckSurveyValidatorForIntegerList.java
  src/main/java/kr/co/teacherforboss/web/dto/MemberRequestDTO.java
Labels: ❤️‍🩹 fix

#56 🩹 #55 Fix: 사전정보 저장 Request Validation 추가
  src/main/java/kr/co/teacherforboss/validation/validator/CheckSurveyValidatorForIntegerList.java
  src/main/java/kr/co/teacherforboss/web/dto/MemberRequestDTO.java
Labels: ❤️‍🩹 fix

#49 🐛[FIX] JWT 토큰 파싱 로직 수정 (Bearer 누락)
  src/main/java/kr/co/teacherforboss/config/jwt/JwtTokenProvider.java
  src/main/java/kr/co/teacherforboss/config/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/kr/co/teacherforboss/web/controller/AuthController.java
Labels: ❤️‍🩹 fix

#54 ✨[FEAT] 회원가입 Request body 필드 추가
  src/main/java/kr/co/teacherforboss/apiPayload/code/status/ErrorStatus.java
  src/main/java/kr/co/teacherforboss/converter/AuthConverter.java
  src/main/java/kr/co/teacherforboss/domain/mapping/AgreementTerm.java
  src/main/java/kr/co/teacherforboss/repository/AgreementTermRepository.java
  src/main/java/kr/co/teacherforboss/service/authService/AuthCommandServiceImpl.java
  src/main/java/kr/co/teacherforboss/validation/annotation/CheckTrueOrFalse.java
  src/main/java/kr/co/teacherforboss/validation/validator/CheckTrueOrFalseValidator.java
  src/main/java/kr/co/teacherforboss/web/dto/AuthRequestDTO.java
Labels: ✨ feature

#50 ✨[FEAT] 소셜로그인 API
  src/main/java/kr/co/teacherforboss/apiPayload/code/status/ErrorStatus.java
  src/main/java/kr/co/teacherforboss/converter/AuthConverter.java
  src/main/java/kr/co/teacherforboss/domain/enums/LoginType.java
  src/main/java/kr/co/teacherforboss/repository/MemberRepository.java
  src/main/java/kr/co/teacherforboss/service/authService/AuthCommandService.java
  src/main/java/kr/co/teacherforboss/service/authService/AuthCommandServiceImpl.java
  src/main/java/kr/co/teacherforboss/util/PasswordUtil.java
  src/main/java/kr/co/teacherforboss/validation/annotation/CheckSocialType.java
  src/main/java/kr/co/teacherforboss/validation/validator/CheckSocialTypeValidator.java
  src/main/java/kr/co/teacherforboss/web/controller/AuthController.java
  src/main/java/kr/co/teacherforboss/web/dto/AuthRequestDTO.java
Labels: ✨ feature

#60 ❤️‍🩹 #57 Fix: 인증번호 5자리로 변경
  src/main/java/kr/co/teacherforboss/config/jwt/filter/JwtExceptionFilter.java
  src/main/java/kr/co/teacherforboss/domain/vo/smsVO/CodeSMS.java
  src/main/java/kr/co/teacherforboss/util/SmsUtil.java
Labels: ❤️‍🩹 fix

#63 🎨[STYLE] delete log
  src/main/java/kr/co/teacherforboss/config/jwt/filter/JwtExceptionFilter.java
  src/main/java/kr/co/teacherforboss/util/SmsUtil.java
Labels: ❤️‍🩹 fix

#65 ⏪ #57 Fix: rewind from number 변수이름
  src/main/java/kr/co/teacherforboss/util/SmsUtil.java
Labels: ❤️‍🩹 fix
