Repository teacher-for-boss/teacher-for-boss-server, pull requests merged in 2024-10, with the labels that each got.

#317 ✨[FEAT] 푸시알림 설정 api
  src/main/java/kr/co/teacherforboss/converter/NotificationConverter.java
  src/main/java/kr/co/teacherforboss/domain/AgreementTerm.java
  src/main/java/kr/co/teacherforboss/domain/NotificationSetting.java
  src/main/java/kr/co/teacherforboss/repository/NotificationSettingRepository.java
  src/main/java/kr/co/teacherforboss/service/notificationService/NotificationCommandService.java
  src/main/java/kr/co/teacherforboss/service/notificationService/NotificationCommandServiceImpl.java
  src/main/java/kr/co/teacherforboss/service/notificationService/NotificationQueryService.java
  src/main/java/kr/co/teacherforboss/service/notificationService/NotificationQueryServiceImpl.java
  src/main/java/kr/co/teacherforboss/web/controller/NotificationController.java
  src/main/java/kr/co/teacherforboss/web/dto/NotificationRequestDTO.java
  src/main/java/kr/co/teacherforboss/web/dto/NotificationResponseDTO.java
Labels: ✨ feature

#318 ✨ [FEAT] 알림
  build.gradle
  src/main/java/kr/co/teacherforboss/TeacherforbossApplication.java
  src/main/java/kr/co/teacherforboss/aop/AwsSnsAspect.java
  src/main/java/kr/co/teacherforboss/aop/NotificationAspect.java
  src/main/java/kr/co/teacherforboss/apiPayload/code/status/ErrorStatus.java
  src/main/java/kr/co/teacherforboss/config/AsyncConfig.java
  src/main/java/kr/co/teacherforboss/config/AwsSnsConfig.java
  src/main/java/kr/co/teacherforboss/config/RedisConfig.java
  src/main/java/kr/co/teacherforboss/config/SchedulerConfig.java
  src/main/java/kr/co/teacherforboss/config/jwt/JwtTokenProvider.java
  src/main/java/kr/co/teacherforboss/config/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/kr/co/teacherforboss/converter/NotificationConverter.java
  src/main/java/kr/co/teacherforboss/domain/Answer.java
  src/main/java/kr/co/teacherforboss/domain/Comment.java
  src/main/java/kr/co/teacherforboss/domain/DeviceToken.java
  src/main/java/kr/co/teacherforboss/domain/Notification.java
  src/main/java/kr/co/teacherforboss/domain/Post.java
  src/main/java/kr/co/teacherforboss/domain/Question.java
  src/main/java/kr/co/teacherforboss/domain/converter/JsonConverter.java
  src/main/java/kr/co/teacherforboss/domain/converter/NotificationLinkDataConverter.java
  src/main/java/kr/co/teacherforboss/domain/converter/StringConverter.java
  src/main/java/kr/co/teacherforboss/domain/converter/SurveyListConverter.java
  src/main/java/kr/co/teacherforboss/domain/enums/NotificationType.java
  src/main/java/kr/co/teacherforboss/domain/vo/notificationVO/NotificationLinkData.java
  src/main/java/kr/co/teacherforboss/domain/vo/notificationVO/NotificationMessage.java
  src/main/java/kr/co/teacherforboss/repository/AnswerRepository.java
  src/main/java/kr/co/teacherforboss/repository/DeviceTokenRepository.java
  src/main/java/kr/co/teacherforboss/repository/MemberRepository.java
  src/main/java/kr/co/teacherforboss/repository/NotificationRepository.java
  src/main/java/kr/co/teacherforboss/repository/PostRepository.java
  src/main/java/kr/co/teacherforboss/repository/QuestionRepository.java
  src/main/java/kr/co/teacherforboss/repository/TeacherSelectInfoRepository.java
  src/main/java/kr/co/teacherforboss/scheduler/HomeScheduler.java
  src/main/java/kr/co/teacherforboss/service/authService/AuthCommandService.java
  src/main/java/kr/co/teacherforboss/service/authService/AuthCommandServiceImpl.java
  src/main/java/kr/co/teacherforboss/service/homeService/HomeQueryServiceImpl.java
  src/main/java/kr/co/teacherforboss/service/notificationService/NotificationQueryService.java
  src/main/java/kr/co/teacherforboss/service/notificationService/NotificationQueryServiceImpl.java
  src/main/java/kr/co/teacherforboss/service/snsService/SnsService.java
  src/main/java/kr/co/teacherforboss/service/snsService/SnsServiceImpl.java
  src/main/java/kr/co/teacherforboss/web/controller/AuthController.java
  src/main/java/kr/co/teacherforboss/web/controller/HomeController.java
  src/main/java/kr/co/teacherforboss/web/controller/NotificationController.java
  src/main/java/kr/co/teacherforboss/web/controller/SnsController.java
  src/main/java/kr/co/teacherforboss/web/dto/AuthRequestDTO.java
  src/main/java/kr/co/teacherforboss/web/dto/NotificationResponseDTO.java
Labels: ✨ feature

#320 ✨[FEAT] 회원가입 시 사업자 인증 로직 주석 처리
  src/main/java/kr/co/teacherforboss/service/authService/AuthCommandServiceImpl.java
Labels: ✨ feature

#321 ❤️‍🩹[FIX] sns endpoint 및 deviceToken 관리 로직 수정
  src/main/java/kr/co/teacherforboss/aop/AwsSnsAspect.java
  src/main/java/kr/co/teacherforboss/aop/NotificationAspect.java
  src/main/java/kr/co/teacherforboss/domain/DeviceToken.java
  src/main/java/kr/co/teacherforboss/repository/NotificationRepository.java
  src/main/java/kr/co/teacherforboss/service/notificationService/NotificationCommandService.java
  src/main/java/kr/co/teacherforboss/service/notificationService/NotificationCommandServiceImpl.java
  src/main/java/kr/co/teacherforboss/service/snsService/SnsServiceImpl.java
  src/main/java/kr/co/teacherforboss/web/controller/SnsController.java
  src/main/java/kr/co/teacherforboss/web/dto/AuthRequestDTO.java
Labels: ❤️‍🩹 fix

#322 ✨[FEAT] 환전 신청 API 수정 (리뷰 반영)
  src/main/java/kr/co/teacherforboss/domain/vo/mailVO/ExchangeMail.java
  src/main/java/kr/co/teacherforboss/service/mailService/MailCommandService.java
  src/main/java/kr/co/teacherforboss/service/mailService/MailCommandServiceImpl.java
  src/main/java/kr/co/teacherforboss/service/paymentService/PaymentCommandServiceImpl.java
  src/main/java/kr/co/teacherforboss/web/dto/PaymentRequestDTO.java
  src/main/resources/templates/exchange.html
Labels: ✨ feature

#323 ✨[FEAT] 채택 플로우 수정 - 조금 정리
  src/main/java/kr/co/teacherforboss/converter/AuthConverter.java
  src/main/java/kr/co/teacherforboss/domain/Answer.java
  src/main/java/kr/co/teacherforboss/domain/AnswerLike.java
  src/main/java/kr/co/teacherforboss/domain/Question.java
  src/main/java/kr/co/teacherforboss/domain/QuestionBookmark.java
  src/main/java/kr/co/teacherforboss/domain/QuestionHashtag.java
  src/main/java/kr/co/teacherforboss/domain/QuestionLike.java
  src/main/java/kr/co/teacherforboss/repository/AnswerRepository.java
  src/main/java/kr/co/teacherforboss/repository/QuestionRepository.java
  src/main/java/kr/co/teacherforboss/scheduler/QuestionScheduler.java
  src/main/java/kr/co/teacherforboss/service/boardService/BoardCommandServiceImpl.java
  src/main/java/kr/co/teacherforboss/service/boardService/BoardQueryServiceImpl.java
Labels: ✨ feature

#326 ✨[FEAT] 회원가입시 사업자 인증 주석 처리
  src/main/java/kr/co/teacherforboss/converter/AuthConverter.java
  src/main/java/kr/co/teacherforboss/service/authService/AuthCommandServiceImpl.java
  src/main/java/kr/co/teacherforboss/web/dto/AuthRequestDTO.java
Labels: ✨ feature

#328 ✨[FEAT] 사업자 정보 관련 정보 주석처리
  src/main/java/kr/co/teacherforboss/domain/TeacherInfo.java
  src/main/java/kr/co/teacherforboss/domain/vo/mailVO/TeacherAuditMail.java
  src/main/java/kr/co/teacherforboss/service/authService/AuthCommandServiceImpl.java
Labels: ✨ feature

#333 🐛[FIX] 프로필 조회 API 탈퇴한 계정으로 조회되는 거 수정
  src/main/java/kr/co/teacherforboss/service/authService/AuthCommandServiceImpl.java
Labels: 🐛 bug
