Repository teacher-for-boss/teacher-for-boss-server, pull requests merged in 2024-06, with the labels that each got.

#180 ✨[FEAT] 티쳐톡 질문 작성 API
  src/main/java/kr/co/teacherforboss/converter/BoardConverter.java
  src/main/java/kr/co/teacherforboss/domain/Question.java
  src/main/java/kr/co/teacherforboss/repository/CategoryRepository.java
  src/main/java/kr/co/teacherforboss/repository/QuestionHashtagRepository.java
  src/main/java/kr/co/teacherforboss/repository/QuestionRepository.java
  src/main/java/kr/co/teacherforboss/service/boardService/BoardCommandService.java
  src/main/java/kr/co/teacherforboss/service/boardService/BoardCommandServiceImpl.java
  src/main/java/kr/co/teacherforboss/web/controller/BoardController.java
  src/main/java/kr/co/teacherforboss/web/dto/BoardRequestDTO.java
  src/main/java/kr/co/teacherforboss/web/dto/BoardResponseDTO.java
Labels: ✨ feature

#204 🐛[FIX] 회원가입 Role 선택 오타 수정
  src/main/java/kr/co/teacherforboss/service/authService/AuthCommandServiceImpl.java
Labels: ❤️‍🩹 fix

#206 ✨[FEAT] 회원가입 API 누락 조건 추가
  src/main/java/kr/co/teacherforboss/service/authService/AuthCommandServiceImpl.java
Labels: ✨ feature

#181 ✨[FEAT] 티쳐톡 질문 수정 API
  src/main/java/kr/co/teacherforboss/apiPayload/code/status/ErrorStatus.java
  src/main/java/kr/co/teacherforboss/converter/BoardConverter.java
  src/main/java/kr/co/teacherforboss/domain/Question.java
  src/main/java/kr/co/teacherforboss/repository/QuestionHashtagRepository.java
  src/main/java/kr/co/teacherforboss/service/boardService/BoardCommandService.java
  src/main/java/kr/co/teacherforboss/service/boardService/BoardCommandServiceImpl.java
  src/main/java/kr/co/teacherforboss/web/controller/BoardController.java
  src/main/java/kr/co/teacherforboss/web/dto/BoardRequestDTO.java
  src/main/java/kr/co/teacherforboss/web/dto/BoardResponseDTO.java
  src/test/java/kr/co/teacherforboss/service/boardService/BoardCommandServiceImplTest.java
Labels: ✨ feature

#208 ❤️‍🩹 [FIX] 회원가입 400 에러 수정
  src/main/java/kr/co/teacherforboss/repository/EmailAuthRepository.java
  src/main/java/kr/co/teacherforboss/repository/PhoneAuthRepository.java
  src/main/java/kr/co/teacherforboss/service/authService/AuthCommandServiceImpl.java
  src/main/java/kr/co/teacherforboss/web/dto/AuthRequestDTO.java
Labels: ❤️‍🩹 fix

#209 ❤️‍🩹 [FIX] 소셜로그인 400 에러 수정
  src/main/java/kr/co/teacherforboss/service/authService/AuthCommandServiceImpl.java
Labels: ❤️‍🩹 fix

#187 ✨[FEAT] 티쳐톡 질문 삭제 API
  src/main/java/kr/co/teacherforboss/converter/BoardConverter.java
  src/main/java/kr/co/teacherforboss/domain/common/BaseEntity.java
  src/main/java/kr/co/teacherforboss/repository/AnswerRepository.java
  src/main/java/kr/co/teacherforboss/repository/QuestionRepository.java
  src/main/java/kr/co/teacherforboss/service/boardService/BoardCommandService.java
  src/main/java/kr/co/teacherforboss/service/boardService/BoardCommandServiceImpl.java
  src/main/java/kr/co/teacherforboss/web/controller/BoardController.java
  src/main/java/kr/co/teacherforboss/web/dto/BoardResponseDTO.java
Labels: ✨ feature

#200 ✨[FEAT] 티쳐톡 답변 작성 API
  src/main/java/kr/co/teacherforboss/apiPayload/code/status/ErrorStatus.java
  src/main/java/kr/co/teacherforboss/converter/BoardConverter.java
  src/main/java/kr/co/teacherforboss/domain/Answer.java
  src/main/java/kr/co/teacherforboss/domain/Question.java
  src/main/java/kr/co/teacherforboss/repository/AnswerRepository.java
  src/main/java/kr/co/teacherforboss/repository/QuestionRepository.java
  src/main/java/kr/co/teacherforboss/service/boardService/BoardCommandService.java
  src/main/java/kr/co/teacherforboss/service/boardService/BoardCommandServiceImpl.java
  src/main/java/kr/co/teacherforboss/web/controller/BoardController.java
  src/main/java/kr/co/teacherforboss/web/dto/BoardRequestDTO.java
  src/main/java/kr/co/teacherforboss/web/dto/BoardResponseDTO.java
Labels: ✨ feature, ❤️‍🩹 fix

#213 ❤️‍🩹 [FIX] 소셜로그인 400 오류 수정
  src/main/java/kr/co/teacherforboss/apiPayload/code/status/ErrorStatus.java
  src/main/java/kr/co/teacherforboss/service/authService/AuthCommandServiceImpl.java
  src/main/java/kr/co/teacherforboss/validation/annotation/CheckRole.java
  src/main/java/kr/co/teacherforboss/validation/validator/CheckRoleValidator.java
  src/main/java/kr/co/teacherforboss/web/dto/AuthRequestDTO.java
Labels: ❤️‍🩹 fix

#196 ✨[FEAT] 프로필 이미지 Presigned URL 저장
  src/main/java/kr/co/teacherforboss/service/s3Service/S3QueryService.java
  src/main/java/kr/co/teacherforboss/service/s3Service/S3QueryServiceImpl.java
  src/main/java/kr/co/teacherforboss/web/controller/S3Controller.java
  src/main/java/kr/co/teacherforboss/web/dto/S3RequestDTO.java
Labels: ✨ feature

#211 ✨[FEAT] 티쳐톡 질문 삭제 API
  src/main/java/kr/co/teacherforboss/converter/BoardConverter.java
  src/main/java/kr/co/teacherforboss/domain/Question.java
  src/main/java/kr/co/teacherforboss/domain/common/BaseEntity.java
  src/main/java/kr/co/teacherforboss/repository/AnswerRepository.java
  src/main/java/kr/co/teacherforboss/repository/QuestionRepository.java
  src/main/java/kr/co/teacherforboss/service/boardService/BoardCommandService.java
  src/main/java/kr/co/teacherforboss/service/boardService/BoardCommandServiceImpl.java
  src/main/java/kr/co/teacherforboss/web/controller/BoardController.java
  src/main/java/kr/co/teacherforboss/web/dto/BoardResponseDTO.java
Labels: ✨ feature

#188 ✨[FEAT] 티쳐톡 질문 좋아요 API
  src/main/java/kr/co/teacherforboss/converter/BoardConverter.java
  src/main/java/kr/co/teacherforboss/domain/QuestionLike.java
  src/main/java/kr/co/teacherforboss/repository/QuestionHashtagRepository.java
  src/main/java/kr/co/teacherforboss/repository/QuestionLikeRepository.java
  src/main/java/kr/co/teacherforboss/service/boardService/BoardCommandService.java
  src/main/java/kr/co/teacherforboss/service/boardService/BoardCommandServiceImpl.java
  src/main/java/kr/co/teacherforboss/web/controller/BoardController.java
  src/main/java/kr/co/teacherforboss/web/dto/BoardResponseDTO.java
Labels: ✨ feature

#224 ❤️‍🩹[FIX] 보스톡 게시글 좋아요 오류 수정
  src/main/java/kr/co/teacherforboss/converter/BoardConverter.java
  src/main/java/kr/co/teacherforboss/repository/PostBookmarkRepository.java
  src/main/java/kr/co/teacherforboss/repository/PostLikeRepository.java
  src/main/java/kr/co/teacherforboss/service/boardService/BoardCommandServiceImpl.java
  src/main/java/kr/co/teacherforboss/service/boardService/BoardQueryServiceImpl.java
Labels: ♻️ refactor, ❤️‍🩹 fix

#220 ✨[FEAT] 티쳐톡 답변 수정 API
  src/main/java/kr/co/teacherforboss/apiPayload/code/status/ErrorStatus.java
  src/main/java/kr/co/teacherforboss/converter/BoardConverter.java
  src/main/java/kr/co/teacherforboss/domain/Answer.java
  src/main/java/kr/co/teacherforboss/repository/AnswerRepository.java
  src/main/java/kr/co/teacherforboss/repository/QuestionRepository.java
  src/main/java/kr/co/teacherforboss/service/boardService/BoardCommandService.java
  src/main/java/kr/co/teacherforboss/service/boardService/BoardCommandServiceImpl.java
  src/main/java/kr/co/teacherforboss/web/controller/BoardController.java
  src/main/java/kr/co/teacherforboss/web/dto/BoardRequestDTO.java
  src/main/java/kr/co/teacherforboss/web/dto/BoardResponseDTO.java
Labels: ✨ feature

#176 ✨[FEAT] 보스톡 게시글 수정
  src/main/java/kr/co/teacherforboss/domain/Post.java
  src/main/java/kr/co/teacherforboss/domain/PostHashtag.java
  src/main/java/kr/co/teacherforboss/domain/Question.java
  src/main/java/kr/co/teacherforboss/domain/common/BaseEntity.java
  src/main/java/kr/co/teacherforboss/repository/HashtagRepository.java
  src/main/java/kr/co/teacherforboss/repository/PostRepository.java
  src/main/java/kr/co/teacherforboss/service/boardService/BoardCommandService.java
  src/main/java/kr/co/teacherforboss/service/boardService/BoardCommandServiceImpl.java
  src/main/java/kr/co/teacherforboss/web/controller/BoardController.java
Labels: ✨ feature

#227 ❤️‍🩹[FIX] 티쳐톡 삭제 시 답변 삭제 수정
  src/main/java/kr/co/teacherforboss/repository/AnswerRepository.java
  src/main/java/kr/co/teacherforboss/service/boardService/BoardCommandServiceImpl.java
Labels: ❤️‍🩹 fix

#225 ✨[FEAT] 티쳐톡 답변 삭제 API
  src/main/java/kr/co/teacherforboss/converter/BoardConverter.java
  src/main/java/kr/co/teacherforboss/repository/AnswerRepository.java
  src/main/java/kr/co/teacherforboss/service/boardService/BoardCommandService.java
  src/main/java/kr/co/teacherforboss/service/boardService/BoardCommandServiceImpl.java
  src/main/java/kr/co/teacherforboss/web/controller/BoardController.java
  src/main/java/kr/co/teacherforboss/web/dto/BoardResponseDTO.java
Labels: ✨ feature

#190 ✨[FEAT] 티쳐톡 질문 북마크
  src/main/java/kr/co/teacherforboss/converter/BoardConverter.java
  src/main/java/kr/co/teacherforboss/domain/QuestionBookmark.java
  src/main/java/kr/co/teacherforboss/repository/QuestionBookmarkRepository.java
  src/main/java/kr/co/teacherforboss/service/boardService/BoardCommandService.java
  src/main/java/kr/co/teacherforboss/service/boardService/BoardCommandServiceImpl.java
  src/main/java/kr/co/teacherforboss/web/controller/BoardController.java
  src/main/java/kr/co/teacherforboss/web/dto/BoardResponseDTO.java
Labels: ✨ feature

#186 ✨[FEAT] 보스톡 댓글 작성 API
  src/main/java/kr/co/teacherforboss/apiPayload/code/status/ErrorStatus.java
  src/main/java/kr/co/teacherforboss/converter/CommentConverter.java
  src/main/java/kr/co/teacherforboss/domain/Comment.java
  src/main/java/kr/co/teacherforboss/repository/CommentRepository.java
  src/main/java/kr/co/teacherforboss/service/commentService/CommentCommandService.java
  src/main/java/kr/co/teacherforboss/service/commentService/CommentCommandServiceImpl.java
  src/main/java/kr/co/teacherforboss/web/dto/CommentRequestDTO.java
  src/main/java/kr/co/teacherforboss/web/dto/CommentResponseDTO.java
Labels: ✨ feature

#195 ✨[FEAT] 티쳐톡 질문 상세 조회 API
  src/main/java/kr/co/teacherforboss/converter/BoardConverter.java
  src/main/java/kr/co/teacherforboss/service/boardService/BoardQueryService.java
  src/main/java/kr/co/teacherforboss/service/boardService/BoardQueryServiceImpl.java
  src/main/java/kr/co/teacherforboss/web/controller/BoardController.java
  src/main/java/kr/co/teacherforboss/web/dto/BoardResponseDTO.java
Labels: ✨ feature

#234 ❤️‍🩹[FIX] res body에 imageUrlList 추가
  src/main/java/kr/co/teacherforboss/config/S3Config.java
  src/main/java/kr/co/teacherforboss/converter/BoardConverter.java
  src/main/java/kr/co/teacherforboss/domain/enums/ImageOrigin.java
  src/main/java/kr/co/teacherforboss/service/s3Service/S3QueryServiceImpl.java
  src/main/java/kr/co/teacherforboss/validation/validator/CheckImageOriginValidator.java
  src/main/java/kr/co/teacherforboss/web/dto/BoardResponseDTO.java
Labels: ❤️‍🩹 fix

#236 ♻️[REFACTOR] 보스톡 댓글 작성 Response 값 변경
  src/main/java/kr/co/teacherforboss/converter/CommentConverter.java
  src/main/java/kr/co/teacherforboss/domain/CommentLike.java
  src/main/java/kr/co/teacherforboss/repository/CommentLikeRepository.java
  src/main/java/kr/co/teacherforboss/service/commentService/CommentCommandService.java
  src/main/java/kr/co/teacherforboss/service/commentService/CommentCommandServiceImpl.java
  src/main/java/kr/co/teacherforboss/web/controller/BoardController.java
  src/main/java/kr/co/teacherforboss/web/dto/BoardRequestDTO.java
  src/main/java/kr/co/teacherforboss/web/dto/BoardResponseDTO.java
  src/main/java/kr/co/teacherforboss/web/dto/CommentRequestDTO.java
  src/main/java/kr/co/teacherforboss/web/dto/CommentResponseDTO.java
Labels: ♻️ refactor

#191 ✨[FEAT] 보스톡 게시물 삭제 API
  src/main/java/kr/co/teacherforboss/apiPayload/code/status/ErrorStatus.java
  src/main/java/kr/co/teacherforboss/converter/BoardConverter.java
  src/main/java/kr/co/teacherforboss/domain/CommentLike.java
  src/main/java/kr/co/teacherforboss/repository/CommentLikeRepository.java
  src/main/java/kr/co/teacherforboss/repository/CommentRepository.java
  src/main/java/kr/co/teacherforboss/repository/PostBookmarkRepository.java
  src/main/java/kr/co/teacherforboss/repository/PostHashtagRepository.java
  src/main/java/kr/co/teacherforboss/repository/PostLikeRepository.java
  src/main/java/kr/co/teacherforboss/repository/PostRepository.java
  src/main/java/kr/co/teacherforboss/service/boardService/BoardCommandService.java
  src/main/java/kr/co/teacherforboss/service/boardService/BoardCommandServiceImpl.java
  src/main/java/kr/co/teacherforboss/web/controller/BoardController.java
  src/main/java/kr/co/teacherforboss/web/dto/BoardResponseDTO.java
Labels: ✨ feature

#218 ✨[FEAT] 보스톡 게시물 상세 조회수 count 증가 로직 추가
  src/main/java/kr/co/teacherforboss/converter/BoardConverter.java
  src/main/java/kr/co/teacherforboss/converter/CommentConverter.java
  src/main/java/kr/co/teacherforboss/domain/Member.java
  src/main/java/kr/co/teacherforboss/domain/Post.java
  src/main/java/kr/co/teacherforboss/domain/PostHashtag.java
  src/main/java/kr/co/teacherforboss/service/boardService/BoardCommandService.java
  src/main/java/kr/co/teacherforboss/service/boardService/BoardCommandServiceImpl.java
  src/main/java/kr/co/teacherforboss/service/boardService/BoardQueryService.java
  src/main/java/kr/co/teacherforboss/service/boardService/BoardQueryServiceImpl.java
  src/main/java/kr/co/teacherforboss/service/commentService/CommentCommandService.java
  src/main/java/kr/co/teacherforboss/service/commentService/CommentCommandServiceImpl.java
  src/main/java/kr/co/teacherforboss/web/controller/BoardController.java
  src/main/java/kr/co/teacherforboss/web/dto/BoardResponseDTO.java
Labels: ✨ feature

#231 ✨[FEAT] 티쳐톡 답변 추천/비추천 API
  src/main/java/kr/co/teacherforboss/converter/BoardConverter.java
  src/main/java/kr/co/teacherforboss/domain/Answer.java
  src/main/java/kr/co/teacherforboss/domain/AnswerLike.java
  src/main/java/kr/co/teacherforboss/repository/AnswerLikeRepository.java
  src/main/java/kr/co/teacherforboss/repository/AnswerRepository.java
  src/main/java/kr/co/teacherforboss/service/boardService/BoardCommandService.java
  src/main/java/kr/co/teacherforboss/service/boardService/BoardCommandServiceImpl.java
  src/main/java/kr/co/teacherforboss/web/controller/BoardController.java
  src/main/java/kr/co/teacherforboss/web/dto/BoardResponseDTO.java
Labels: ✨ feature

#238 ✨[FEAT] 티쳐톡 답변 채택 API
  src/main/java/kr/co/teacherforboss/converter/BoardConverter.java
  src/main/java/kr/co/teacherforboss/domain/Answer.java
  src/main/java/kr/co/teacherforboss/domain/Question.java
  src/main/java/kr/co/teacherforboss/service/boardService/BoardCommandService.java
  src/main/java/kr/co/teacherforboss/service/boardService/BoardCommandServiceImpl.java
  src/main/java/kr/co/teacherforboss/web/controller/BoardController.java
  src/main/java/kr/co/teacherforboss/web/dto/BoardResponseDTO.java
Labels: ✨ feature
