Repository teacher-for-boss/teacher-for-boss-server, pull requests merged in 2024-04, with the labels that each got.

#136 ✨[FEAT] 시험 리스트 조회 API
  src/main/java/kr/co/teacherforboss/apiPayload/code/status/ErrorStatus.java
  src/main/java/kr/co/teacherforboss/config/ExamConfig.java
  src/main/java/kr/co/teacherforboss/converter/ExamConverter.java
  src/main/java/kr/co/teacherforboss/repository/ExamRepository.java
  src/main/java/kr/co/teacherforboss/repository/MemberExamRepository.java
  src/main/java/kr/co/teacherforboss/repository/TagRepository.java
  src/main/java/kr/co/teacherforboss/service/examService/ExamQueryService.java
  src/main/java/kr/co/teacherforboss/service/examService/ExamQueryServiceImpl.java
  src/main/java/kr/co/teacherforboss/web/controller/ExamController.java
  src/main/java/kr/co/teacherforboss/web/dto/ExamResponseDTO.java
Labels: ✨ feature

#141 📝 [DOCS] 리드미 꾸미기
  README.md
Labels: 📝 docs

#138 ♻️ [REFACTOR] 같은 업종 사장님 평균 점수 조회 API 쿼리 리팩토링 & 동시성 테스트
  src/main/java/kr/co/teacherforboss/domain/Member.java
  src/main/java/kr/co/teacherforboss/repository/ExamRepository.java
  src/main/java/kr/co/teacherforboss/repository/MemberExamRepository.java
  src/test/java/kr/co/teacherforboss/service/authService/AuthCommandServiceImplTest.java
  src/test/java/kr/co/teacherforboss/service/examService/ExamQueryServiceImplTest.java
  src/test/java/kr/co/teacherforboss/service/memberService/MemberQueryServiceImplTest.java
  src/test/java/kr/co/teacherforboss/util/AuthTestUtil.java
  src/test/java/kr/co/teacherforboss/util/ExamTestUtil.java
Labels: ♻️ refactor, ✅ test
